import { z } from "zod";

export const supplierSchema = z.object({
  name: z.string().min(3),
  contactPerson: z.string().min(3),
  mobileNo: z.string().min(3),
  email: z.string().min(3),
  ascLicenseNo: z.string().min(3),
  ascLicenseEndorsementDate: z.string().min(3),
  ascLicenseExpiryDate: z.string().min(3),
  bankAccountName: z.string().min(3),
  bankAccountNo: z.string().min(3),
  bankBranchName: z.string().min(3),
  tin: z.string().min(3),
  bin: z.string().min(3),
  tinPicturePath: z.string().min(3),
  binPicturePath: z.string().min(3),
  assetValue: z.string(),
  contractCapacity: z.string(),
  otherBusiness: z.string().optional(),
  otherBusinessLicensesCopyPath: z.string().min(3),
  securityClearanceValidity: z.string().min(3),
  supplierPhotosPath: z.string().min(3),
  signaturePicturePath: z.string().min(3),
});
