import { z } from "zod";

export const supplierSchema = z.object({
  name: z.string().min(3),
  contactPerson: z.string().min(3),
  mobileNo: z.string().min(3),
  email: z.string().min(3),
  ascLicenseNo: z.string().min(3),
  ascLicenseEndorsementDate: z.string().nullable(),
  ascLicenseExpiryDate: z.string().nullable(),
  bankAccountName: z.string().min(3),
  bankAccountNo: z.string().min(3),
  bankBranchName: z.string().min(3),
  tin: z.string().min(3),
  bin: z.string().min(3),
  tinPicturePath: z.string().nullable(),
  binPicturePath: z.string().nullable(),
  assetValue: z.number().nullable(),
  contractCapacity: z.number().nullable(),
  otherBusiness: z.boolean().nullable(),
  securityClearanceValidity: z.string().nullable(),
  supplierPhotosPath: z.string().nullable(),
  signaturePicturePath: z.string().nullable(),
  otherBusinessLicensesCopyPath: z.string().nullable(),
});
